version: '3'
services:
  logan-middle-dingtalk:
    image: registry.logan.xiaopeng.local/logan_test/prometheus-webhook-dingtalk:1.0.0
    container_name: logan-middle-dingtalk
    restart: unless-stopped
    ports:
      - 8060:8060
#    networks:
#      - logan
    volumes:
      - ./template/default.tmpl:/alert.tmpl:rw
    command:
#      - /bin/sh
#      - -c
#      - /bin/prometheus-webhook-dingtalk
      - --ding.profile=loganXMan=https://oapi.dingtalk.com/robot/send?access_token=b54a9357d9ac97cf74369b3d928a150d8bb75d6dd22cf710b949a6abc11f0c02
      - --template.file=/alert.tmpl
